In [1]:
import pandas as pd
from jdatetime import datetime, date
from IPython import display

In [2]:
df = pd.read_excel("data.xlsx")

In [3]:
df['ReserveStatus'].unique()

array(['دریافت شده', 'ارسال نشده', 'دریافت نشده', 'منقضی شده'],
      dtype=object)

In [4]:
def convert_ReserveStatus(x):
    if(x == 'دریافت نشده' or x == 'ارسال نشده' or x == 'منقضی شده'):
        return 0
    return 1

In [5]:
df['ReserveStatus'] = df['ReserveStatus'].apply(convert_ReserveStatus)

In [6]:
df

,PersonId,Reserveid,Gender,Price,DateReserve,Name,FoodName,Count,ReserveStatus,CollegeName,...,FieldName,DegreeCode,DegreeName,RestaurantName,GroupName,EducationSession,PersonType,Comment,Reception,ReceptionType
0,44905,6607259,مرد_x000D_\n,100000.0,1402/12/1,شام,زرشك پلوبامرغ+میوه,1,1,دانشکدگان ‌فنی,...,مهندسي كامپيوتر,10,كارشناسي پـيوسته,سطح شهر-رودکی-قدس 2,خوابگاه سطح شهر-رودکی(قدس 2),روزانه_x000D_\n,دانشجو,بدون نظر,NaN,1
1,26019,6666529,زن,80000.0,1402/12/1,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,1,1,دانشکدگان علوم‌,...,آمار,10,كارشناسي پـيوسته,خوابگاه-چمران-خواهران,خوابگاه چمران,روزانه_x000D_\n,دانشجو,بدون نظر,بارکد فراموشی,2
2,112964,6595770,مرد_x000D_\n,80000.0,1402/12/1,شام,خوراک فلافل+سس کچاپ(تکنفره)+گوجه فرنگی حلقه ای...,1,1,ادبیات‌ و علوم‌ انسانی‌,...,زبان و ادبيات فارسي,10,كارشناسي پـيوسته,سطح شهر-سیزده آبان,خوابگاه سطح شهر-سیزده آبان(پسران),روزانه_x000D_\n,دانشجو,بدون نظر,NaN,1
3,113319,6668633,مرد_x000D_\n,80000.0,1402/12/1,شام,خوراک فلافل+سس کچاپ(تکنفره)+گوجه فرنگی حلقه ای...,1,1,حقوق‌ و علوم‌ سیاسی‌,...,حقوق,10,كارشناسي پـيوسته,سطح شهر-قدس,خوابگاه سطح شهر-قدس,روزانه_x000D_\n,دانشجو,بدون نظر,NaN,1
4,159242,6596422,زن,80000.0,1402/12/1,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,1,1,زبان ها و ادبیات‌ خارجی‌,...,زبان و ادبيات انگليسي,10,كارشناسي پـيوسته,خوابگاه-چمران-خواهران,خوابگاه چمران,روزانه_x000D_\n,دانشجو,خوب,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272551,157916,6751941,مرد_x000D_\n,100000.0,1402/12/9,شام,چلو خورش قیمه سیب زمینی+دوغ,1,1,دانشکدگان ‌فنی,...,مهندسي برق,10,كارشناسي پـيوسته,سطح شهر-قدس 3,خوابگاه سطح شهر-قدس 3,روزانه_x000D_\n,دانشجو,بدون نظر,NaN,1
272552,113686,6730482,زن,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,0,حقوق‌ و علوم‌ سیاسی‌,...,حقوق,10,كارشناسي پـيوسته,دانشکده-سلف مهر,دانشکده حقوق,روزانه_x000D_\n,دانشجو,بدون نظر,NaN,0
272553,143428,6693856,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,1,دانشکدگان هنرهای‌ زیبا,...,مرمت و احياي ابنيه و بافت هاي تاريخي - حفاظت و...,15,كارشناسي ارشد ناپيوسته,دانشکده-سلف هنرهای زیبا,دانشکده هنرهای زیبا,شبانه(نوبت دوم),دانشجو,بدون نظر,بارکد فراموشی,2
272554,143807,6725223,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,1,دانشکدگان ‌فنی,...,مهندسي عمران گرايش مهندسي محيط زيست,15,كارشناسي ارشد ناپيوسته,دانشکده-سلف فنی1-16 آذر -برادران-کارکنان-برادران,دانشکده فنی1-16 آذر(برادران),شبانه(نوبت دوم),دانشجو,بدون نظر,بارکد فراموشی,2
272555,26784,6724830,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,0,دانشکدگان علوم‌,...,زيست فناوري,10,كارشناسي پـيوسته,دانشکده-سلف علوم,دانشکده علوم,روزانه_x000D_\n,دانشجو,بدون نظر,NaN,0

In [7]:
df['ReserveStatus'].unique()

array([1, 0])

In [8]:
df['Reception'].unique()

array([nan, 'بارکد فراموشی', 'کد فراموشی'], dtype=object)

In [9]:
def convert_Reception(x):
    if(x == 'کد فراموشی' or x == 'بارکد فراموشی'):
        return 1
    return 0

In [10]:
df['Reception'] = df['Reception'].apply(convert_Reception)

In [11]:
df['Reception'].unique()

array([0, 1])

In [12]:
def apply_recive_with_card(row):
    if row['Reception'] == 0 and row['ReserveStatus'] == 1:
        return 1
    return 0

In [13]:
df['reciev_with_card'] = df.apply(apply_recive_with_card,axis=1)

In [14]:
def apply_reciev_with_code(row):
    if row['Reception'] == 1 and row['ReserveStatus'] == 1:
        return 1
    return 0

In [15]:
df['reciev_with_code'] = df.apply(apply_reciev_with_code,axis=1)

In [16]:
def apply_dont_reciev(row):
    if row['ReserveStatus'] == 0:
        return 1
    return 0

In [17]:
df['dont_reciev'] = df.apply(apply_dont_reciev,axis=1)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272556 entries, 0 to 272555
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   PersonId          272556 non-null  int64
 1   Reserveid         272556 non-null  int64
 2   Gender            272556 non-null  object
 3   Price             272553 non-null  float64
 4   DateReserve       272556 non-null  object
 5   Name              272556 non-null  object
 6   FoodName          272556 non-null  object
 7   Count             272556 non-null  int64
 8   ReserveStatus     272556 non-null  int64
 9   CollegeName       272556 non-null  object
 10  CollegeCode       272554 non-null  float64
 11  FieldCode         272556 non-null  int64
 12  FieldName         272556 non-null  object
 13  DegreeCode        272556 non-null  int64
 14  DegreeName        272556 non-null  object
 15  RestaurantName    272556 non-null  object
 16  GroupName         272556 non-null  object
 17  EducationSession  272556 non-null  object
 18  PersonType        272556 non-null  object
 19  Comment           272556 non-null  object
 20  Reception         272556 non-null  int64
 21  ReceptionType     272556 non-null  int64
 22  reciev_with_card  272556 non-null  int64
 23  reciev_with_code  272556 non-null  int64
 24  dont_reciev       272556 non-null  int64
dtypes: float64(2), int64(11), object(12)
memory usage: 52.0+ MB

In [19]:
df['DateReserve'] = df['DateReserve'].astype(str)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272556 entries, 0 to 272555
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   PersonId          272556 non-null  int64
 1   Reserveid         272556 non-null  int64
 2   Gender            272556 non-null  object
 3   Price             272553 non-null  float64
 4   DateReserve       272556 non-null  object
 5   Name              272556 non-null  object
 6   FoodName          272556 non-null  object
 7   Count             272556 non-null  int64
 8   ReserveStatus     272556 non-null  int64
 9   CollegeName       272556 non-null  object
 10  CollegeCode       272554 non-null  float64
 11  FieldCode         272556 non-null  int64
 12  FieldName         272556 non-null  object
 13  DegreeCode        272556 non-null  int64
 14  DegreeName        272556 non-null  object
 15  RestaurantName    272556 non-null  object
 16  GroupName         272556 non-null  object
 17  EducationSession  272556 non-null  object
 18  PersonType        272556 non-null  object
 19  Comment           272556 non-null  object
 20  Reception         272556 non-null  int64
 21  ReceptionType     272556 non-null  int64
 22  reciev_with_card  272556 non-null  int64
 23  reciev_with_code  272556 non-null  int64
 24  dont_reciev       272556 non-null  int64
dtypes: float64(2), int64(11), object(12)
memory usage: 52.0+ MB

In [21]:
df

,PersonId,Reserveid,Gender,Price,DateReserve,Name,FoodName,Count,ReserveStatus,CollegeName,...,RestaurantName,GroupName,EducationSession,PersonType,Comment,Reception,ReceptionType,reciev_with_card,reciev_with_code,dont_reciev
0,44905,6607259,مرد_x000D_\n,100000.0,1402/12/1,شام,زرشك پلوبامرغ+میوه,1,1,دانشکدگان ‌فنی,...,سطح شهر-رودکی-قدس 2,خوابگاه سطح شهر-رودکی(قدس 2),روزانه_x000D_\n,دانشجو,بدون نظر,0,1,1,0,0
1,26019,6666529,زن,80000.0,1402/12/1,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,1,1,دانشکدگان علوم‌,...,خوابگاه-چمران-خواهران,خوابگاه چمران,روزانه_x000D_\n,دانشجو,بدون نظر,1,2,0,1,0
2,112964,6595770,مرد_x000D_\n,80000.0,1402/12/1,شام,خوراک فلافل+سس کچاپ(تکنفره)+گوجه فرنگی حلقه ای...,1,1,ادبیات‌ و علوم‌ انسانی‌,...,سطح شهر-سیزده آبان,خوابگاه سطح شهر-سیزده آبان(پسران),روزانه_x000D_\n,دانشجو,بدون نظر,0,1,1,0,0
3,113319,6668633,مرد_x000D_\n,80000.0,1402/12/1,شام,خوراک فلافل+سس کچاپ(تکنفره)+گوجه فرنگی حلقه ای...,1,1,حقوق‌ و علوم‌ سیاسی‌,...,سطح شهر-قدس,خوابگاه سطح شهر-قدس,روزانه_x000D_\n,دانشجو,بدون نظر,0,1,1,0,0
4,159242,6596422,زن,80000.0,1402/12/1,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,1,1,زبان ها و ادبیات‌ خارجی‌,...,خوابگاه-چمران-خواهران,خوابگاه چمران,روزانه_x000D_\n,دانشجو,خوب,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272551,157916,6751941,مرد_x000D_\n,100000.0,1402/12/9,شام,چلو خورش قیمه سیب زمینی+دوغ,1,1,دانشکدگان ‌فنی,...,سطح شهر-قدس 3,خوابگاه سطح شهر-قدس 3,روزانه_x000D_\n,دانشجو,بدون نظر,0,1,1,0,0
272552,113686,6730482,زن,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,0,حقوق‌ و علوم‌ سیاسی‌,...,دانشکده-سلف مهر,دانشکده حقوق,روزانه_x000D_\n,دانشجو,بدون نظر,0,0,0,0,1
272553,143428,6693856,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,1,دانشکدگان هنرهای‌ زیبا,...,دانشکده-سلف هنرهای زیبا,دانشکده هنرهای زیبا,شبانه(نوبت دوم),دانشجو,بدون نظر,1,2,0,1,0
272554,143807,6725223,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,1,دانشکدگان ‌فنی,...,دانشکده-سلف فنی1-16 آذر -برادران-کارکنان-برادران,دانشکده فنی1-16 آذر(برادران),شبانه(نوبت دوم),دانشجو,بدون نظر,1,2,0,1,0
272555,26784,6724830,مرد_x000D_\n,100000.0,1402/12/9,ناهار,زرشك پلوبامرغ+خوراک لوبیا,1,0,دانشکدگان علوم‌,...,دانشکده-سلف علوم,دانشکده علوم,روزانه_x000D_\n,دانشجو,بدون نظر,0,0,0,0,1

In [22]:
grouped = df.groupby(['DateReserve', 'RestaurantName','Name','FoodName','Gender'])
result = grouped.agg({
    'reciev_with_card': 'sum',
    'reciev_with_code': 'sum',
    'dont_reciev': 'sum'
})

In [23]:
result = result.reset_index()

In [24]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,زن,217,19,17
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ+دوغ,زن,269,33,25
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل+پوره سیب زمینی+ماست موسیر,زن,60,11,7
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش+ماست موسیر,زن,104,20,16
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,مرد_x000D_\n,138,9,12
...,...,...,...,...,...,...,...,...
3347,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني+میوه,زن,73,7,7
3348,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ+سیب زمینی سرخ کرده+سس کچاپ(تکنف...,زن,101,16,22
3349,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ+سیب زمینی سرخ کرده+سس کچاپ(تکنف...,مرد_x000D_\n,59,12,3
3350,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی+خرما,زن,305,63,31
3351,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی+خرما,مرد_x000D_\n,347,41,45

In [25]:
result['Name'].unique()

array(['شام', 'ناهار', 'صبحانه', 'سحر'], dtype=object)

In [26]:
result = result.drop(result[result['Name'] == 'سحر'].index)
result = result.drop(result[result['Name'] == 'صبحانه'].index)

In [27]:
result = result.reset_index(drop=True)

In [28]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,زن,217,19,17
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ+دوغ,زن,269,33,25
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل+پوره سیب زمینی+ماست موسیر,زن,60,11,7
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش+ماست موسیر,زن,104,20,16
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل+دوغ+سس کچاپ(تکنفره)+گوجه فرنگی حلق...,مرد_x000D_\n,138,9,12
...,...,...,...,...,...,...,...,...
3116,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني+میوه,زن,73,7,7
3117,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ+سیب زمینی سرخ کرده+سس کچاپ(تکنف...,زن,101,16,22
3118,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ+سیب زمینی سرخ کرده+سس کچاپ(تکنف...,مرد_x000D_\n,59,12,3
3119,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی+خرما,زن,305,63,31
3120,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی+خرما,مرد_x000D_\n,347,41,45

In [29]:
result['Name'].unique()

array(['شام', 'ناهار'], dtype=object)

In [30]:
result['FoodName'].nunique()

185

In [31]:
def delete_definition(x):
    sep = '+'
    stripped = x.split(sep, 1)[0]
    return stripped
result['FoodName'] = result['FoodName'].apply(delete_definition)

In [32]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد_x000D_\n,138,9,12
...,...,...,...,...,...,...,...,...
3116,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7
3117,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22
3118,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد_x000D_\n,59,12,3
3119,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31
3120,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد_x000D_\n,347,41,45

In [33]:
for i in result['FoodName'].unique():
    print(i)

خوراک فلافل
زرشك پلوبامرغ
خوراک دلمه فلفل
عدس پلو با گوشت و كشمش
خوراک ماكارونی با قارچ
چلوكباب كوبیده
استانبولی پلو با مرغ
ساندویچ همبرگر
خرید از بوفه روزانه
خرید از بوفه هفتگی (5 روز)
خوراک لوبیا چیتی(رستوران آزاد-کشاورزی)
ساندویچ بندری(رستوران آزاد-کشاورزی)
پیتزا مخلوط(رستوران آزاد-کشاورزی)
ژامبون مرغ(رستوران آزاد-کشاورزی)
عدس پلو با سویا(رستوران آزاد-کشاورزی)
هات داگ با قارچ و پنیر(رستوران آزاد-کشاورزی)
همبرگر(رستوران آزاد-کشاورزی)
پیتزا سبزیجات(رستوران آزاد-کشاورزی)
چیز برگر(رستوران آزاد-کشاورزی)
خوراک میرزاقاسمی
خوراک چیكن استروگانوف
ساندویچ فلافل
خوراک كشك بادمجان
چلو خورش قورمه سبزی
ماکارونی با سویا(رستوران آزاد-کشاورزی)
چلوكباب كوبیده نگيني
خوراک کوکو سیب زمینی
خوراک آبگوشت
باقلاپلو با مرغ
خوراک بیف استروگانوف
خوراک ناگت مرغ
چلو خورش فسنجان(مرغ)
خوراک سالاد الویه
لوبیا پلو باگوشت
خوراک کوردن بلو
چلوجوجه كباب
چلوكوبيده مرغ(1 سيخ)
استانبولی پلو با گوشت
خوراک گراتن با سبزیجات
خوراک عدسی(رستوران آزاد-کشاورزی)
خوراک مرغ سوخاری
چلو خورش كرفس
خوراک كوفته تبریزی
ساندویچ مرغ و قارچ
خوراک گوجه بادمجان(رستوران آزاد-کشاورزی)
استانبولی پلو با سویا(رستوران آزاد-کشاورزی)
چلوگوشت
استانبولی با گوشت
خوراک شنیسل مرغ
سبزی پلو ماهی
سبزی پلو با ماهی قزل آلا
چلو خورش قیمه سیب زمینی
چلو خورش قیمه بادمجان
خوراک نخود فرنگی با مرغ
خوراک سالاد ماكاروني
سبزی پلوباگوشت
لوبیا پلو با سویا(رستوران آزاد-کشاورزی)
چلومرغ مخلوط
 چلوجوجه كباب
خوراک كتلت
چلو خورش مسما بادمجان با مرغ
خوراک بادمجان(یتیمچه)
رشته پلو با گوشت
سبزی پلو با تن ماهی
خوراک کوکو سبزی
خوراک قارچ و گوشت
باقلاپلو با گوشت
خوراک میرزاقاسمی
خوراک جوجه چینی
لوبیا پلو با مرغ
شوید باقلاباگوشت
خوراک نخود فرنگی با گوشت
خوراک كشك بادمجان
خوراک مرغ و قارچ
استانبولی پلو با گوشت

In [34]:
def total_nember(row):
    return row['reciev_with_card']+row['reciev_with_code'] + row['dont_reciev']
result['total'] = result.apply(total_nember,axis=1)

In [35]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد_x000D_\n,138,9,12,159
...,...,...,...,...,...,...,...,...,...
3116,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87
3117,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139
3118,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد_x000D_\n,59,12,3,74
3119,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399
3120,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد_x000D_\n,347,41,45,433

In [36]:
result = result[result['total']> 3]

In [37]:
result = result.reset_index(drop=True)

In [38]:
def delete_definition(x):
    sep = '('
    stripped = x.split(sep, 1)[0]
    return stripped
result['FoodName'] = result['FoodName'].apply(delete_definition)

In [39]:
result['FoodName'].nunique()

72

In [40]:
result = result[result['RestaurantName'] != 'کشاورزی- رستوران آزاد']

In [41]:
result.reset_index(drop=True)

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد_x000D_\n,138,9,12,159
...,...,...,...,...,...,...,...,...,...
2699,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87
2700,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139
2701,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد_x000D_\n,59,12,3,74
2702,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399
2703,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد_x000D_\n,347,41,45,433

In [42]:
result['FoodName'].unique()

array(['خوراک فلافل', 'زرشك پلوبامرغ', 'خوراک دلمه فلفل',
       'عدس پلو با گوشت و كشمش', 'خوراک ماكارونی با قارچ',
       'چلوكباب كوبیده', 'استانبولی پلو با مرغ', 'ساندویچ همبرگر',
       'خرید از بوفه روزانه', 'خرید از بوفه هفتگی ', 'خوراک میرزاقاسمی ',
       'خوراک چیكن استروگانوف', 'ساندویچ فلافل', 'خوراک كشك بادمجان',
       'چلو خورش قورمه سبزی', 'چلوكباب كوبیده نگيني',
       'خوراک کوکو سیب زمینی', 'خوراک آبگوشت', 'باقلاپلو با مرغ',
       'خوراک بیف استروگانوف', 'خوراک ناگت مرغ', 'چلو خورش فسنجان',
       'خوراک سالاد الویه', 'لوبیا پلو باگوشت', 'خوراک کوردن بلو',
       'چلوجوجه كباب', 'چلوكوبيده مرغ', 'استانبولی پلو با گوشت ',
       'خوراک گراتن با سبزیجات', 'خوراک مرغ سوخاری', 'چلو خورش كرفس',
       'خوراک كوفته تبریزی', 'ساندویچ مرغ و قارچ', 'چلوگوشت ',
       'استانبولی با گوشت', 'خوراک شنیسل مرغ', 'سبزی پلو ماهی',
       'سبزی پلو با ماهی قزل آلا', 'چلو خورش قیمه سیب زمینی',
       'چلو خورش قیمه بادمجان', 'خوراک نخود فرنگی با مرغ',
       'خوراک سالاد ماكاروني', 'سبزی پلوباگوشت', 'چلومرغ مخلوط',
       ' چلوجوجه كباب ', 'خوراک كتلت', 'چلو خورش مسما بادمجان با مرغ',
       'خوراک بادمجان', 'رشته پلو با گوشت', 'سبزی پلو با تن ماهی',
       'خوراک کوکو سبزی', 'خوراک قارچ و گوشت', 'باقلاپلو با گوشت',
       'خوراک میرزاقاسمی', 'خوراک جوجه چینی', 'لوبیا پلو با مرغ',
       'شوید باقلاباگوشت', 'خوراک نخود فرنگی با گوشت',
       'خوراک كشك بادمجان ', 'خوراک مرغ و قارچ', 'استانبولی پلو با گوشت'],
      dtype=object)

In [43]:
result = result[result['FoodName'] != 'خرید از بوفه روزانه']
result = result[result['FoodName'] != 'خرید از بوفه هفتگی ']
result = result.reset_index(drop = True)
result['FoodName'].unique()

array(['خوراک فلافل', 'زرشك پلوبامرغ', 'خوراک دلمه فلفل',
       'عدس پلو با گوشت و كشمش', 'خوراک ماكارونی با قارچ',
       'چلوكباب كوبیده', 'استانبولی پلو با مرغ', 'ساندویچ همبرگر',
       'خوراک میرزاقاسمی ', 'خوراک چیكن استروگانوف', 'ساندویچ فلافل',
       'خوراک كشك بادمجان', 'چلو خورش قورمه سبزی', 'چلوكباب كوبیده نگيني',
       'خوراک کوکو سیب زمینی', 'خوراک آبگوشت', 'باقلاپلو با مرغ',
       'خوراک بیف استروگانوف', 'خوراک ناگت مرغ', 'چلو خورش فسنجان',
       'خوراک سالاد الویه', 'لوبیا پلو باگوشت', 'خوراک کوردن بلو',
       'چلوجوجه كباب', 'چلوكوبيده مرغ', 'استانبولی پلو با گوشت ',
       'خوراک گراتن با سبزیجات', 'خوراک مرغ سوخاری', 'چلو خورش كرفس',
       'خوراک كوفته تبریزی', 'ساندویچ مرغ و قارچ', 'چلوگوشت ',
       'استانبولی با گوشت', 'خوراک شنیسل مرغ', 'سبزی پلو ماهی',
       'سبزی پلو با ماهی قزل آلا', 'چلو خورش قیمه سیب زمینی',
       'چلو خورش قیمه بادمجان', 'خوراک نخود فرنگی با مرغ',
       'خوراک سالاد ماكاروني', 'سبزی پلوباگوشت', 'چلومرغ مخلوط',
       ' چلوجوجه كباب ', 'خوراک كتلت', 'چلو خورش مسما بادمجان با مرغ',
       'خوراک بادمجان', 'رشته پلو با گوشت', 'سبزی پلو با تن ماهی',
       'خوراک کوکو سبزی', 'خوراک قارچ و گوشت', 'باقلاپلو با گوشت',
       'خوراک میرزاقاسمی', 'خوراک جوجه چینی', 'لوبیا پلو با مرغ',
       'شوید باقلاباگوشت', 'خوراک نخود فرنگی با گوشت',
       'خوراک كشك بادمجان ', 'خوراک مرغ و قارچ', 'استانبولی پلو با گوشت'],
      dtype=object)

In [44]:
def select_name(x):
    if x == 'شوید باقلاباگوشت':
        return 'چلو شوید باقلاباگوشت'
    elif x == 'استانبولی با گوشت':
        return 'استانبولی پلو با گوشت'
    else:
        return x
result['FoodName'] = result['FoodName'].apply(select_name)

In [45]:
def select_type(x):
    if 'چلو' in x:
        return "berenji"
    elif 'پلو' in x:
        return "berenji"
    elif 'خوراک' in  x:
        return "khorak"
    elif 'ساندویچ' in  x:
        return "khorak"

In [46]:
result['type'] = result['FoodName'].apply(select_type)
result['type'].unique()

array(['khorak', 'berenji'], dtype=object)

In [47]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total,type
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253,khorak
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327,berenji
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78,khorak
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140,berenji
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد_x000D_\n,138,9,12,159,khorak
...,...,...,...,...,...,...,...,...,...,...
2655,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87,khorak
2656,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139,khorak
2657,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد_x000D_\n,59,12,3,74,khorak
2658,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399,berenji
2659,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد_x000D_\n,347,41,45,433,berenji

In [48]:
def delete__x000D(x):
    return x.replace("_x000D_\n","")
result['Gender']=result['Gender'].apply(delete__x000D)
result['Gender'].unique()

array(['زن', 'مرد'], dtype=object)

In [49]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total,type
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253,khorak
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327,berenji
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78,khorak
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140,berenji
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد,138,9,12,159,khorak
...,...,...,...,...,...,...,...,...,...,...
2655,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87,khorak
2656,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139,khorak
2657,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد,59,12,3,74,khorak
2658,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399,berenji
2659,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد,347,41,45,433,berenji

In [50]:
from persiantools.jdatetime import JalaliDate
def convert_date_to_weekday(d):
    '''
    d: str, date in format 'yyyy/mm/dd'
    return: int, weekday of the date in range [0, 6]
    '''
    return JalaliDate(*map(int, d.split('/'))).weekday()
convert_date_to_weekday(result['DateReserve'].iloc[0])
result['DayOfWeek'] = result['DateReserve'].map(convert_date_to_weekday)

In [51]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total,type,DayOfWeek
0,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253,khorak,3
1,1402/12/1,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327,berenji,3
2,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78,khorak,3
3,1402/12/1,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140,berenji,3
4,1402/12/1,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد,138,9,12,159,khorak,3
...,...,...,...,...,...,...,...,...,...,...,...
2655,1402/12/9,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87,khorak,4
2656,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139,khorak,4
2657,1402/12/9,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد,59,12,3,74,khorak,4
2658,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399,berenji,4
2659,1402/12/9,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد,347,41,45,433,berenji,4

In [52]:
def str_to_date(d, gregorian:bool=False) -> JalaliDate:
    out = JalaliDate(*map(int, d.split('/')))
    if gregorian:
        return out.to_gregorian()
    return out
result['DateReserve'] = df['DateReserve'].map(str_to_date)
result['DateReserveGregorian'] = df['DateReserve'].map(lambda d: str_to_date(d, True)).astype('datetime64[ns]')

result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2660 entries, 0 to 2659
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DateReserve           2660 non-null   object
 1   RestaurantName        2660 non-null   object
 2   Name                  2660 non-null   object
 3   FoodName              2660 non-null   object
 4   Gender                2660 non-null   object
 5   reciev_with_card      2660 non-null   int64
 6   reciev_with_code      2660 non-null   int64
 7   dont_reciev           2660 non-null   int64
 8   total                 2660 non-null   int64
 9   type                  2660 non-null   object
 10  DayOfWeek             2660 non-null   int64
 11  DateReserveGregorian  2660 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(6)
memory usage: 249.5+ KB

In [53]:
result

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total,type,DayOfWeek,DateReserveGregorian
0,1402-12-01,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253,khorak,3,2024-02-20
1,1402-12-01,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327,berenji,3,2024-02-20
2,1402-12-01,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78,khorak,3,2024-02-20
3,1402-12-01,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140,berenji,3,2024-02-20
4,1402-12-01,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد,138,9,12,159,khorak,3,2024-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...
2655,1402-12-01,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87,khorak,4,2024-02-20
2656,1402-12-01,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139,khorak,4,2024-02-20
2657,1402-12-01,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد,59,12,3,74,khorak,4,2024-02-20
2658,1402-12-01,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399,berenji,4,2024-02-20
2659,1402-12-01,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد,347,41,45,433,berenji,4,2024-02-20

In [54]:
from bs4 import BeautifulSoup
from holiday import Holiday, HolidayCalculator
holidays = []
for i in [1401,1402,1403]:
    with open(f"date/date_{i}.html", 'r') as file:
        file_content = file.read()
        soup = BeautifulSoup(file_content, 'html.parser')
        h = Holiday(soup)
        holidays_year = h.get_holidays(add_noroze=True, add_thursday=True)
        holidays.extend(holidays_year)
holidays

[JalaliDate(1401, 1, 1, Doshanbeh),
 JalaliDate(1401, 1, 2, Seshanbeh),
 JalaliDate(1401, 1, 3, Chaharshanbeh),
 JalaliDate(1401, 1, 4, Panjshanbeh),
 JalaliDate(1401, 1, 5, Jomeh),
 JalaliDate(1401, 1, 12, Jomeh),
 JalaliDate(1401, 1, 13, Shanbeh),
 JalaliDate(1401, 1, 19, Jomeh),
 JalaliDate(1401, 1, 26, Jomeh),
 JalaliDate(1401, 2, 2, Jomeh),
 JalaliDate(1401, 2, 3, Shanbeh),
 JalaliDate(1401, 2, 9, Jomeh),
 JalaliDate(1401, 2, 13, Seshanbeh),
 JalaliDate(1401, 2, 14, Chaharshanbeh),
 JalaliDate(1401, 2, 16, Jomeh),
 JalaliDate(1401, 2, 23, Jomeh),
 JalaliDate(1401, 2, 30, Jomeh),
 JalaliDate(1401, 3, 6, Jomeh),
 JalaliDate(1401, 3, 13, Jomeh),
 JalaliDate(1401, 3, 14, Shanbeh),
 JalaliDate(1401, 3, 15, Yekshanbeh),
 JalaliDate(1401, 3, 20, Jomeh),
 JalaliDate(1401, 3, 27, Jomeh),
 JalaliDate(1401, 4, 3, Jomeh),
 JalaliDate(1401, 4, 10, Jomeh),
 JalaliDate(1401, 4, 17, Jomeh),
 JalaliDate(1401, 4, 19, Yekshanbeh),
 JalaliDate(1401, 4, 24, Jomeh),
 JalaliDate(1401, 4, 27, Doshanbeh),
 JalaliDate(1401, 4, 31, Jomeh),
 JalaliDate(1401, 5, 7, Jomeh),
 JalaliDate(1401, 5, 14, Jomeh),
 JalaliDate(1401, 5, 16, Yekshanbeh),
 JalaliDate(1401, 5, 17, Doshanbeh),
 JalaliDate(1401, 5, 21, Jomeh),
 JalaliDate(1401, 5, 28, Jomeh),
 JalaliDate(1401, 6, 4, Jomeh),
 JalaliDate(1401, 6, 11, Jomeh),
 JalaliDate(1401, 6, 18, Jomeh),
 JalaliDate(1401, 6, 25, Jomeh),
 JalaliDate(1401, 6, 26, Shanbeh),
 JalaliDate(1401, 7, 1, Jomeh),
 JalaliDate(1401, 7, 3, Yekshanbeh),
 JalaliDate(1401, 7, 5, Seshanbeh),
 JalaliDate(1401, 7, 8, Jomeh),
 JalaliDate(1401, 7, 13, Chaharshanbeh),
 JalaliDate(1401, 7, 15, Jomeh),
 JalaliDate(1401, 7, 22, Jomeh),
 JalaliDate(1401, 7, 29, Jomeh),
 JalaliDate(1401, 8, 6, Jomeh),
 JalaliDate(1401, 8, 13, Jomeh),
 JalaliDate(1401, 8, 20, Jomeh),
 JalaliDate(1401, 8, 27, Jomeh),
 JalaliDate(1401, 9, 4, Jomeh),
 JalaliDate(1401, 9, 11, Jomeh),
 JalaliDate(1401, 9, 18, Jomeh),
 JalaliDate(1401, 9, 25, Jomeh),
 JalaliDate(1401, 10, 2, Jomeh),
 JalaliDate(1401, 10, 6, Seshanbeh),
 JalaliDate(1401, 10, 9, Jomeh),
 JalaliDate(1401, 10, 16, Jomeh),
 JalaliDate(1401, 10, 23, Jomeh),
 JalaliDate(1401, 10, 30, Jomeh),
 JalaliDate(1401, 11, 7, Jomeh),
 JalaliDate(1401, 11, 14, Jomeh),
 JalaliDate(1401, 11, 15, Shanbeh),
 JalaliDate(1401, 11, 21, Jomeh),
 JalaliDate(1401, 11, 22, Shanbeh),
 JalaliDate(1401, 11, 28, Jomeh),
 JalaliDate(1401, 11, 29, Shanbeh),
 JalaliDate(1401, 12, 5, Jomeh),
 JalaliDate(1401, 12, 12, Jomeh),
 JalaliDate(1401, 12, 17, Chaharshanbeh),
 JalaliDate(1401, 12, 19, Jomeh),
 JalaliDate(1401, 12, 26, Jomeh),
 JalaliDate(1401, 12, 29, Doshanbeh),
 JalaliDate(1401, 1, 6, Shanbeh),
 JalaliDate(1401, 1, 7, Yekshanbeh),
 JalaliDate(1401, 1, 8, Doshanbeh),
 JalaliDate(1401, 1, 9, Seshanbeh),
 JalaliDate(1401, 1, 10, Chaharshanbeh),
 JalaliDate(1401, 1, 11, Panjshanbeh),
 JalaliDate(1401, 1, 18, Panjshanbeh),
 JalaliDate(1401, 1, 25, Panjshanbeh),
 JalaliDate(1401, 2, 1, Panjshanbeh),
 JalaliDate(1401, 2, 8, Panjshanbeh),
 JalaliDate(1401, 2, 15, Panjshanbeh),
 JalaliDate(1401, 2, 22, Panjshanbeh),
 JalaliDate(1401, 2, 29, Panjshanbeh),
 JalaliDate(1401, 3, 5, Panjshanbeh),
 JalaliDate(1401, 3, 12, Panjshanbeh),
 JalaliDate(1401, 3, 19, Panjshanbeh),
 JalaliDate(1401, 3, 26, Panjshanbeh),
 JalaliDate(1401, 4, 2, Panjshanbeh),
 JalaliDate(1401, 4, 9, Panjshanbeh),
 JalaliDate(1401, 4, 16, Panjshanbeh),
 JalaliDate(1401, 4, 23, Panjshanbeh),
 JalaliDate(1401, 4, 30, Panjshanbeh),
 JalaliDate(1401, 5, 6, Panjshanbeh),
 JalaliDate(1401, 5, 13, Panjshanbeh),
 JalaliDate(1401, 5, 20, Panjshanbeh),
 JalaliDate(1401, 5, 27, Panjshanbeh),
 JalaliDate(1401, 6, 3, Panjshanbeh),
 JalaliDate(1401, 6, 10, Panjshanbeh),
 JalaliDate(1401, 6, 17, Panjshanbeh),
 JalaliDate(1401, 6, 24, Panjshanbeh),
 JalaliDate(1401, 6, 31, Panjshanbeh),
 JalaliDate(1401, 7, 7, Panjshanbeh),
 JalaliDate(1401, 7, 14, Panjshanbeh),
 JalaliDate(1401, 7, 21, Panjshanbeh),
 JalaliDate(1401, 7, 28, Panjshanbeh),
 JalaliDate(1401, 8, 5, Panjshanbeh),
 JalaliDate(1401, 8, 12, Panjshanbeh),
 JalaliDate(1401, 8, 19, Panjshanbeh),
 JalaliDate(1401, 8, 26, Panjshanbeh),
 JalaliDate(1401, 9, 3, Panjshanbeh),
 JalaliDate(1401, 9, 10, Panjshanbeh),
 JalaliDate(1401, 9, 17, Panjshanbeh),
 JalaliDate(1401, 9, 24, Panjshanbeh),
 JalaliDate(1401, 10, 1, Panjshanbeh),
 JalaliDate(1401, 10, 8, Panjshanbeh),
 JalaliDate(1401, 10, 15, Panjshanbeh),
 JalaliDate(1401, 10, 22, Panjshanbeh),
 JalaliDate(1401, 10, 29, Panjshanbeh),
 JalaliDate(1401, 11, 6, Panjshanbeh),
 JalaliDate(1401, 11, 13, Panjshanbeh),
 JalaliDate(1401, 11, 20, Panjshanbeh),
 JalaliDate(1401, 11, 27, Panjshanbeh),
 JalaliDate(1401, 12, 4, Panjshanbeh),
 JalaliDate(1401, 12, 11, Panjshanbeh),
 JalaliDate(1401, 12, 18, Panjshanbeh),
 JalaliDate(1401, 12, 25, Panjshanbeh),
 JalaliDate(1402, 1, 1, Seshanbeh),
 JalaliDate(1402, 1, 2, Chaharshanbeh),
 JalaliDate(1402, 1, 3, Panjshanbeh),
 JalaliDate(1402, 1, 4, Jomeh),
 JalaliDate(1402, 1, 11, Jomeh),
 JalaliDate(1402, 1, 12, Shanbeh),
 JalaliDate(1402, 1, 13, Yekshanbeh),
 JalaliDate(1402, 1, 18, Jomeh),
 JalaliDate(1402, 1, 23, Chaharshanbeh),
 JalaliDate(1402, 1, 25, Jomeh),
 JalaliDate(1402, 2, 1, Jomeh),
 JalaliDate(1402, 2, 2, Shanbeh),
 JalaliDate(1402, 2, 3, Yekshanbeh),
 JalaliDate(1402, 2, 8, Jomeh),
 JalaliDate(1402, 2, 15, Jomeh),
 JalaliDate(1402, 2, 22, Jomeh),
 JalaliDate(1402, 2, 26, Seshanbeh),
 JalaliDate(1402, 2, 29, Jomeh),
 JalaliDate(1402, 3, 5, Jomeh),
 JalaliDate(1402, 3, 12, Jomeh),
 JalaliDate(1402, 3, 14, Yekshanbeh),
 JalaliDate(1402, 3, 15, Doshanbeh),
 JalaliDate(1402, 3, 19, Jomeh),
 JalaliDate(1402, 3, 26, Jomeh),
 JalaliDate(1402, 4, 2, Jomeh),
 JalaliDate(1402, 4, 8, Panjshanbeh),
 JalaliDate(1402, 4, 9, Jomeh),
 JalaliDate(1402, 4, 16, Jomeh),
 JalaliDate(1402, 4, 23, Jomeh),
 JalaliDate(1402, 4, 30, Jomeh),
 JalaliDate(1402, 5, 5, Panjshanbeh),
 JalaliDate(1402, 5, 6, Jomeh),
 JalaliDate(1402, 5, 13, Jomeh),
 JalaliDate(1402, 5, 20, Jomeh),
 JalaliDate(1402, 5, 27, Jomeh),
 JalaliDate(1402, 6, 3, Jomeh),
 JalaliDate(1402, 6, 10, Jomeh),
 JalaliDate(1402, 6, 15, Chaharshanbeh),
 JalaliDate(1402, 6, 17, Jomeh),
 JalaliDate(1402, 6, 23, Panjshanbeh),
 JalaliDate(1402, 6, 24, Jomeh),
 JalaliDate(1402, 6, 25, Shanbeh),
 JalaliDate(1402, 6, 31, Jomeh),
 JalaliDate(1402, 7, 2, Yekshanbeh),
 JalaliDate(1402, 7, 7, Jomeh),
 JalaliDate(1402, 7, 11, Seshanbeh),
 JalaliDate(1402, 7, 14, Jomeh),
 JalaliDate(1402, 7, 21, Jomeh),
 JalaliDate(1402, 7, 28, Jomeh),
 JalaliDate(1402, 8, 5, Jomeh),
 JalaliDate(1402, 8, 12, Jomeh),
 JalaliDate(1402, 8, 19, Jomeh),
 JalaliDate(1402, 8, 26, Jomeh),
 JalaliDate(1402, 9, 3, Jomeh),
 JalaliDate(1402, 9, 10, Jomeh),
 JalaliDate(1402, 9, 17, Jomeh),
 JalaliDate(1402, 9, 24, Jomeh),
 JalaliDate(1402, 9, 26, Yekshanbeh),
 JalaliDate(1402, 10, 1, Jomeh),
 JalaliDate(1402, 10, 8, Jomeh),
 JalaliDate(1402, 10, 15, Jomeh),
 JalaliDate(1402, 10, 22, Jomeh),
 JalaliDate(1402, 10, 29, Jomeh),
 JalaliDate(1402, 11, 5, Panjshanbeh),
 JalaliDate(1402, 11, 6, Jomeh),
 JalaliDate(1402, 11, 13, Jomeh),
 JalaliDate(1402, 11, 19, Panjshanbeh),
 JalaliDate(1402, 11, 20, Jomeh),
 JalaliDate(1402, 11, 22, Yekshanbeh),
 JalaliDate(1402, 11, 27, Jomeh),
 JalaliDate(1402, 12, 4, Jomeh),
 JalaliDate(1402, 12, 6, Yekshanbeh),
 JalaliDate(1402, 12, 11, Jomeh),
 JalaliDate(1402, 12, 18, Jomeh),
 JalaliDate(1402, 12, 25, Jomeh),
 JalaliDate(1402, 12, 29, Seshanbeh),
 JalaliDate(1402, 1, 5, Shanbeh),
 JalaliDate(1402, 1, 6, Yekshanbeh),
 JalaliDate(1402, 1, 7, Doshanbeh),
 JalaliDate(1402, 1, 8, Seshanbeh),
 JalaliDate(1402, 1, 9, Chaharshanbeh),
 JalaliDate(1402, 1, 10, Panjshanbeh),
 JalaliDate(1402, 1, 17, Panjshanbeh),
 JalaliDate(1402, 1, 24, Panjshanbeh),
 JalaliDate(1402, 1, 31, Panjshanbeh),
 JalaliDate(1402, 2, 7, Panjshanbeh),
 JalaliDate(1402, 2, 14, Panjshanbeh),
 JalaliDate(1402, 2, 21, Panjshanbeh),
 JalaliDate(1402, 2, 28, Panjshanbeh),
 JalaliDate(1402, 3, 4, Panjshanbeh),
 JalaliDate(1402, 3, 11, Panjshanbeh),
 JalaliDate(1402, 3, 18, Panjshanbeh),
 JalaliDate(1402, 3, 25, Panjshanbeh),
 JalaliDate(1402, 4, 1, Panjshanbeh),
 JalaliDate(1402, 4, 15, Panjshanbeh),
 JalaliDate(1402, 4, 22, Panjshanbeh),
 JalaliDate(1402, 4, 29, Panjshanbeh),
 JalaliDate(1402, 5, 12, Panjshanbeh),
 JalaliDate(1402, 5, 19, Panjshanbeh),
 JalaliDate(1402, 5, 26, Panjshanbeh),
 JalaliDate(1402, 6, 2, Panjshanbeh),
 JalaliDate(1402, 6, 9, Panjshanbeh),
 JalaliDate(1402, 6, 16, Panjshanbeh),
 JalaliDate(1402, 6, 30, Panjshanbeh),
 JalaliDate(1402, 7, 6, Panjshanbeh),
 JalaliDate(1402, 7, 13, Panjshanbeh),
 JalaliDate(1402, 7, 20, Panjshanbeh),
 JalaliDate(1402, 7, 27, Panjshanbeh),
 JalaliDate(1402, 8, 4, Panjshanbeh),
 JalaliDate(1402, 8, 11, Panjshanbeh),
 JalaliDate(1402, 8, 18, Panjshanbeh),
 JalaliDate(1402, 8, 25, Panjshanbeh),
 JalaliDate(1402, 9, 2, Panjshanbeh),
 JalaliDate(1402, 9, 9, Panjshanbeh),
 JalaliDate(1402, 9, 16, Panjshanbeh),
 JalaliDate(1402, 9, 23, Panjshanbeh),
 JalaliDate(1402, 9, 30, Panjshanbeh),
 JalaliDate(1402, 10, 7, Panjshanbeh),
 JalaliDate(1402, 10, 14, Panjshanbeh),
 JalaliDate(1402, 10, 21, Panjshanbeh),
 JalaliDate(1402, 10, 28, Panjshanbeh),
 JalaliDate(1402, 11, 12, Panjshanbeh),
 JalaliDate(1402, 11, 26, Panjshanbeh),
 JalaliDate(1402, 12, 3, Panjshanbeh),
 JalaliDate(1402, 12, 10, Panjshanbeh),
 JalaliDate(1402, 12, 17, Panjshanbeh),
 JalaliDate(1402, 12, 24, Panjshanbeh),
 JalaliDate(1403, 1, 1, Chaharshanbeh),
 JalaliDate(1403, 1, 2, Panjshanbeh),
 JalaliDate(1403, 1, 3, Jomeh),
 JalaliDate(1403, 1, 4, Shanbeh),
 JalaliDate(1403, 1, 10, Jomeh),
 JalaliDate(1403, 1, 12, Yekshanbeh),
 JalaliDate(1403, 1, 13, Doshanbeh),
 JalaliDate(1403, 1, 17, Jomeh),
 JalaliDate(1403, 1, 22, Chaharshanbeh),
 JalaliDate(1403, 1, 23, Panjshanbeh),
 JalaliDate(1403, 1, 24, Jomeh),
 JalaliDate(1403, 1, 31, Jomeh),
 JalaliDate(1403, 2, 7, Jomeh),
 JalaliDate(1403, 2, 14, Jomeh),
 JalaliDate(1403, 2, 15, Shanbeh),
 JalaliDate(1403, 2, 21, Jomeh),
 JalaliDate(1403, 2, 28, Jomeh),
 JalaliDate(1403, 3, 4, Jomeh),
 JalaliDate(1403, 3, 11, Jomeh),
 JalaliDate(1403, 3, 14, Doshanbeh),
 JalaliDate(1403, 3, 15, Seshanbeh),
 JalaliDate(1403, 3, 18, Jomeh),
 JalaliDate(1403, 3, 25, Jomeh),
 JalaliDate(1403, 3, 28, Doshanbeh),
 JalaliDate(1403, 4, 1, Jomeh),
 JalaliDate(1403, 4, 5, Seshanbeh),
 JalaliDate(1403, 4, 8, Jomeh),
 JalaliDate(1403, 4, 15, Jomeh),
 JalaliDate(1403, 4, 22, Jomeh),
 JalaliDate(1403, 4, 25, Doshanbeh),
 JalaliDate(1403, 4, 26, Seshanbeh),
 JalaliDate(1403, 4, 29, Jomeh),
 JalaliDate(1403, 5, 5, Jomeh),
 JalaliDate(1403, 5, 12, Jomeh),
 JalaliDate(1403, 5, 19, Jomeh),
 JalaliDate(1403, 5, 26, Jomeh),
 JalaliDate(1403, 6, 2, Jomeh),
 JalaliDate(1403, 6, 4, Yekshanbeh),
 JalaliDate(1403, 6, 9, Jomeh),
 JalaliDate(1403, 6, 12, Doshanbeh),
 JalaliDate(1403, 6, 14, Chaharshanbeh),
 JalaliDate(1403, 6, 16, Jomeh),
 JalaliDate(1403, 6, 22, Panjshanbeh),
 JalaliDate(1403, 6, 23, Jomeh),
 JalaliDate(1403, 6, 30, Jomeh),
 JalaliDate(1403, 6, 31, Shanbeh),
 JalaliDate(1403, 7, 6, Jomeh),
 JalaliDate(1403, 7, 13, Jomeh),
 JalaliDate(1403, 7, 20, Jomeh),
 JalaliDate(1403, 7, 27, Jomeh),
 JalaliDate(1403, 8, 4, Jomeh),
 JalaliDate(1403, 8, 11, Jomeh),
 JalaliDate(1403, 8, 18, Jomeh),
 JalaliDate(1403, 8, 25, Jomeh),
 JalaliDate(1403, 9, 2, Jomeh),
 JalaliDate(1403, 9, 9, Jomeh),
 JalaliDate(1403, 9, 15, Panjshanbeh),
 JalaliDate(1403, 9, 16, Jomeh),
 JalaliDate(1403, 9, 23, Jomeh),
 JalaliDate(1403, 9, 30, Jomeh),
 JalaliDate(1403, 10, 7, Jomeh),
 JalaliDate(1403, 10, 14, Jomeh),
 JalaliDate(1403, 10, 21, Jomeh),
 JalaliDate(1403, 10, 25, Seshanbeh),
 JalaliDate(1403, 10, 28, Jomeh),
 JalaliDate(1403, 11, 5, Jomeh),
 JalaliDate(1403, 11, 9, Seshanbeh),
 JalaliDate(1403, 11, 12, Jomeh),
 JalaliDate(1403, 11, 19, Jomeh),
 JalaliDate(1403, 11, 22, Doshanbeh),
 JalaliDate(1403, 11, 26, Jomeh),
 JalaliDate(1403, 12, 3, Jomeh),
 JalaliDate(1403, 12, 10, Jomeh),
 JalaliDate(1403, 12, 17, Jomeh),
 JalaliDate(1403, 12, 24, Jomeh),
 JalaliDate(1403, 12, 29, Chaharshanbeh),
 JalaliDate(1403, 12, 30, Panjshanbeh),
 JalaliDate(1403, 1, 5, Yekshanbeh),
 JalaliDate(1403, 1, 6, Doshanbeh),
 JalaliDate(1403, 1, 7, Seshanbeh),
 JalaliDate(1403, 1, 8, Chaharshanbeh),
 JalaliDate(1403, 1, 9, Panjshanbeh),
 JalaliDate(1403, 1, 11, Shanbeh),
 JalaliDate(1403, 1, 16, Panjshanbeh),
 JalaliDate(1403, 1, 30, Panjshanbeh),
 JalaliDate(1403, 2, 6, Panjshanbeh),
 JalaliDate(1403, 2, 13, Panjshanbeh),
 JalaliDate(1403, 2, 20, Panjshanbeh),
 JalaliDate(1403, 2, 27, Panjshanbeh),
 JalaliDate(1403, 3, 3, Panjshanbeh),
 JalaliDate(1403, 3, 10, Panjshanbeh),
 JalaliDate(1403, 3, 17, Panjshanbeh),
 JalaliDate(1403, 3, 24, Panjshanbeh),
 JalaliDate(1403, 3, 31, Panjshanbeh),
 JalaliDate(1403, 4, 7, Panjshanbeh),
 JalaliDate(1403, 4, 14, Panjshanbeh),
 JalaliDate(1403, 4, 21, Panjshanbeh),
 JalaliDate(1403, 4, 28, Panjshanbeh),
 JalaliDate(1403, 5, 4, Panjshanbeh),
 JalaliDate(1403, 5, 11, Panjshanbeh),
 JalaliDate(1403, 5, 18, Panjshanbeh),
 JalaliDate(1403, 5, 25, Panjshanbeh),
 JalaliDate(1403, 6, 1, Panjshanbeh),
 JalaliDate(1403, 6, 8, Panjshanbeh),
 JalaliDate(1403, 6, 15, Panjshanbeh),
 JalaliDate(1403, 6, 29, Panjshanbeh),
 JalaliDate(1403, 7, 5, Panjshanbeh),
 JalaliDate(1403, 7, 12, Panjshanbeh),
 JalaliDate(1403, 7, 19, Panjshanbeh),
 JalaliDate(1403, 7, 26, Panjshanbeh),
 JalaliDate(1403, 8, 3, Panjshanbeh),
 JalaliDate(1403, 8, 10, Panjshanbeh),
 JalaliDate(1403, 8, 17, Panjshanbeh),
 JalaliDate(1403, 8, 24, Panjshanbeh),
 JalaliDate(1403, 9, 1, Panjshanbeh),
 JalaliDate(1403, 9, 8, Panjshanbeh),
 JalaliDate(1403, 9, 22, Panjshanbeh),
 JalaliDate(1403, 9, 29, Panjshanbeh),
 JalaliDate(1403, 10, 6, Panjshanbeh),
 JalaliDate(1403, 10, 13, Panjshanbeh),
 JalaliDate(1403, 10, 20, Panjshanbeh),
 JalaliDate(1403, 10, 27, Panjshanbeh),
 JalaliDate(1403, 11, 4, Panjshanbeh),
 JalaliDate(1403, 11, 11, Panjshanbeh),
 JalaliDate(1403, 11, 18, Panjshanbeh),
 JalaliDate(1403, 11, 25, Panjshanbeh),
 JalaliDate(1403, 12, 2, Panjshanbeh),
 JalaliDate(1403, 12, 9, Panjshanbeh),
 JalaliDate(1403, 12, 16, Panjshanbeh),
 JalaliDate(1403, 12, 23, Panjshanbeh)]

In [66]:
h_map = dict()
n = 5
for day in result['DateReserve'].unique():
    calculator = HolidayCalculator(holidays, day, have_weekend=False)
    h_map[day] = {
        'HolidayInWeekCount': calculator.get_holidays_this_week(True),
        'HolidayInWeek': calculator.get_holidays_this_week(),
        'NextHoliday': calculator.get_n_next_holiday(n),
        'PreviousHoliday': calculator.get_n_previous_holiday(n)
    }

result['HolidayInWeekCount'] = result['DateReserve'].map(lambda d: h_map[d]['HolidayInWeekCount'])

for i in ['PreviousHoliday', 'NextHoliday']:
    for j in range(5):
        result[f'{i}_{j+1}'] = result['DateReserve'].map(lambda d: h_map[d][i][j])

display(pd.DataFrame(h_map).T)
display(result)

,HolidayInWeek,HolidayInWeekCount,NextHoliday,PreviousHoliday
1402-12-01,[],0,"[5, 28, 29, 32, 33]","[9, 65, 140, 149, 157]"

,DateReserve,RestaurantName,Name,FoodName,Gender,reciev_with_card,reciev_with_code,dont_reciev,total,type,...,PreviousHoliday_1,PreviousHoliday_2,PreviousHoliday_3,PreviousHoliday_4,PreviousHoliday_5,NextHoliday_1,NextHoliday_2,NextHoliday_3,NextHoliday_4,NextHoliday_5
0,1402-12-01,خوابگاه- فاطمیه -خواهران,شام,خوراک فلافل,زن,217,19,17,253,khorak,...,9,65,140,149,157,5,28,29,32,33
1,1402-12-01,خوابگاه- فاطمیه -خواهران,شام,زرشك پلوبامرغ,زن,269,33,25,327,berenji,...,9,65,140,149,157,5,28,29,32,33
2,1402-12-01,خوابگاه- فاطمیه -خواهران,ناهار,خوراک دلمه فلفل,زن,60,11,7,78,khorak,...,9,65,140,149,157,5,28,29,32,33
3,1402-12-01,خوابگاه- فاطمیه -خواهران,ناهار,عدس پلو با گوشت و كشمش,زن,104,20,16,140,berenji,...,9,65,140,149,157,5,28,29,32,33
4,1402-12-01,خوابگاه-ساختمان 6-برادران,شام,خوراک فلافل,مرد,138,9,12,159,khorak,...,9,65,140,149,157,5,28,29,32,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2655,1402-12-01,کشاورزی- سلف خوابگاه خواهران,شام,خوراک سالاد ماكاروني,زن,73,7,7,87,khorak,...,9,65,140,149,157,5,28,29,32,33
2656,1402-12-01,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,زن,101,16,22,139,khorak,...,9,65,140,149,157,5,28,29,32,33
2657,1402-12-01,کشاورزی- سلف مرکزی,ناهار,خوراک ناگت مرغ,مرد,59,12,3,74,khorak,...,9,65,140,149,157,5,28,29,32,33
2658,1402-12-01,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,زن,305,63,31,399,berenji,...,9,65,140,149,157,5,28,29,32,33
2659,1402-12-01,کشاورزی- سلف مرکزی,ناهار,سبزی پلو با تن ماهی,مرد,347,41,45,433,berenji,...,9,65,140,149,157,5,28,29,32,33